
import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Graphics2D;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Christian Parra
 */
public class Ventana extends javax.swing.JFrame {

    public int[] arreglo;

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
        setSize(640, 480);//tamaño 
        setLocationRelativeTo(null);
    }

    
    public void generarArreglo(int numElementos) {
        Random r = new Random();
        arreglo = new int[numElementos];
        for (int i = 0; i < arreglo.length; i++) {
            arreglo[i] = r.nextInt(50);
        }
    }

    
    public void dibujar(int[] arreglo) {
        int w = 10;
        int dist = 2;
        int inicioX = 30; 
        Graphics2D g = (Graphics2D) canvas1.getGraphics(); 
        g.setColor(getBackground());
        g.fillRect(0, 0, canvas1.getWidth(), canvas1.getHeight());
        g.setStroke(new BasicStroke(w));
        g.setColor(Color.red);
        for (int x = 0; x < arreglo.length; x++) {
            int v = arreglo[x] * 10;
            g.drawLine(x * (w + dist) + inicioX, canvas1.getHeight(), x * (w + dist) + inicioX, canvas1.getHeight() - v);
        }
        try { //Para mostrar cada intercambio realizado
            Thread.sleep(100);
        } catch (InterruptedException ex) {
            Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    
    public String arregloString(int[] arreglo) {
        String res = "";
        for (int i : arreglo) {
            if (res.length() > 0) {
                res += ", ";
            }
            res += i;
        }
        return res;
    }

    public void bubbleSort(int[] aiDatos) {
        boolean sorted = false;
        int Final = aiDatos.length - 1;
        while (!sorted) {
            sorted = true;
            for (int i = 0; i < aiDatos.length - 1; i++) {
                if (aiDatos[i] > aiDatos[i + 1]) {
                    swap(aiDatos, i, i + 1);
                    sorted = false;
                }
            }
            Final--;
            dibujar(aiDatos);
        }
    }

    public void swap(int[] aiDatos, int i, int j) {
        int iTemp = aiDatos[i];
        aiDatos[i] = aiDatos[j];
        aiDatos[j] = iTemp;
    }

    public void quickSort(int[] aiDatos, int Primero, int Final) {
        int i, j, Pivote;
        i = Primero;
        j = Final;
        Pivote = aiDatos[(Primero + Final) / 2];
        do {
            while (aiDatos[i] < Pivote) {
                i++;
            }
            while (aiDatos[j] > Pivote) {
                j--;
            }
            if (i <= j) {
                int iTemp = aiDatos[i];
                aiDatos[i] = aiDatos[j];
                aiDatos[j] = iTemp;
                i++;
                j--;
                dibujar(aiDatos);
            }
        } while (i <= j);
        if (Primero < j) {
            quickSort(aiDatos, Primero, j);

        }
        if (i < Final) {
            quickSort(aiDatos, i, Final);
        }
    }

    //Eficiencia es O(n^2) -- Comparaciones
    //O(N)-- Intercambio
    public void selectionSort(int[] aiDatos) {
        for (int i = 0; i < aiDatos.length; i++) { //Recorrer todos
            int iMin = i; //La primer posición
            for (int j = i + 1; j < aiDatos.length; j++) { //HAY QUE COMPARAR CON EL SIGUIENTE, POR ESO j;i
                if (aiDatos[j] < aiDatos[iMin]) {
                    iMin = j;
                    dibujar(aiDatos);
                }

            }
            if (iMin != i) { //Intercambiar dato
                int iTemp = aiDatos[i]; //Necesitamos crear una variable temporal y ahí guardamos i
                aiDatos[i] = aiDatos[iMin];
                aiDatos[iMin] = iTemp;
                dibujar(aiDatos);
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        canvas1 = new java.awt.Canvas();
        btnBubble = new javax.swing.JButton();
        btnQuick = new javax.swing.JButton();
        btnSel = new javax.swing.JButton();
        txtOriginal = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtOrdenado = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnBubble.setText("bubbleSort");
        btnBubble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBubbleActionPerformed(evt);
            }
        });

        btnQuick.setText("quickSort");
        btnQuick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuickActionPerformed(evt);
            }
        });

        btnSel.setText("selectionSort");
        btnSel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelActionPerformed(evt);
            }
        });

        jLabel1.setText("Original");

        jLabel2.setText("Ordenado");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(canvas1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnSel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnQuick, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnBubble, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 38, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtOriginal)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtOrdenado))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(btnBubble)
                .addGap(28, 28, 28)
                .addComponent(btnQuick)
                .addGap(27, 27, 27)
                .addComponent(btnSel)
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtOriginal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtOrdenado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(canvas1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBubbleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBubbleActionPerformed
        generarArreglo(10);
        txtOriginal.setText(arregloString(arreglo));
        dibujar(arreglo);
        bubbleSort(arreglo);
        txtOrdenado.setText(arregloString(arreglo));
    }//GEN-LAST:event_btnBubbleActionPerformed

    private void btnQuickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuickActionPerformed
        generarArreglo(10);
        txtOriginal.setText(arregloString(arreglo));
        dibujar(arreglo);
        quickSort(arreglo, 0, arreglo.length - 1);
        txtOrdenado.setText(arregloString(arreglo));
    }//GEN-LAST:event_btnQuickActionPerformed

    private void btnSelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelActionPerformed
        generarArreglo(10);
        txtOriginal.setText(arregloString(arreglo));
        dibujar(arreglo);
        selectionSort(arreglo);
        txtOrdenado.setText(arregloString(arreglo));
    }//GEN-LAST:event_btnSelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBubble;
    private javax.swing.JButton btnQuick;
    private javax.swing.JButton btnSel;
    private java.awt.Canvas canvas1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtOrdenado;
    private javax.swing.JTextField txtOriginal;
    // End of variables declaration//GEN-END:variables
}
